name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
          os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenBLAS
        run: sudo apt-get install -y libopenblas-dev

      - name: Build wheel for CPython 3.7
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: cp37-manylinux_x86_64
          CIBW_ENVIRONMENT: BLA_VENDOR=OpenBLAS CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/openblas-pthread

      - name: Build wheel for CPython 3.8
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: cp38-manylinux_x86_64
          CIBW_ENVIRONMENT: BLA_VENDOR=OpenBLAS CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/openblas-pthread

      - name: Build wheel for CPython 3.9
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: cp39-manylinux_x86_64
          CIBW_ENVIRONMENT: BLA_VENDOR=OpenBLAS CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/openblas-pthread

      - name: Build wheel for CPython 3.10
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: cp310-manylinux_x86_64
          CIBW_ENVIRONMENT: BLA_VENDOR=OpenBLAS CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/openblas-pthread

      - name: Build wheel for CPython 3.11
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: cp311-manylinux_x86_64
          CIBW_ENVIRONMENT: BLA_VENDOR=OpenBLAS CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/openblas-pthread

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Upload release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./wheelhouse/*.whl
